// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApmjoLvG5miJUan2JkMmiiTUPnkbC-3-E',
    appId: '1:402175534147:web:d6ca0cd18bb603a3ad60f6',
    messagingSenderId: '402175534147',
    projectId: 'vorbindchat',
    authDomain: 'vorbindchat.firebaseapp.com',
    storageBucket: 'vorbindchat.appspot.com',
    databaseURL: 'https://vorbindchat-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3FmZdWV6FMk5HuVWXI-OYWDC1S5OqwSo',
    appId: '1:402175534147:android:eda1e80c00a4c97ead60f6',
    messagingSenderId: '402175534147',
    projectId: 'vorbindchat',
    storageBucket: 'vorbindchat.appspot.com',
    databaseURL: 'https://vorbindchat-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjrQ3xkGzBwEZqi6xvoFsdeP3gz0GCezU',
    appId: '1:402175534147:ios:ad74b77af3fd34a1ad60f6',
    messagingSenderId: '402175534147',
    projectId: 'vorbindchat',
    storageBucket: 'vorbindchat.appspot.com',
    iosBundleId: 'com.example.vorbind',
    databaseURL: 'https://vorbindchat-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjrQ3xkGzBwEZqi6xvoFsdeP3gz0GCezU',
    appId: '1:402175534147:ios:8eef229e8b592e61ad60f6',
    messagingSenderId: '402175534147',
    projectId: 'vorbindchat',
    storageBucket: 'vorbindchat.appspot.com',
    iosBundleId: 'com.example.vorbind.RunnerTests',
    databaseURL: 'https://vorbindchat-default-rtdb.firebaseio.com/',
  );
}
